version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/code/

    environment:
      - .env.local
  #   depends_on:
  #     - db
  # db:
  #   image: postgres:16.1-bookworm
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres